config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  patch "/edit", to: "players#update" 
  resources:players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end

  def new
  	@player = Player.new
  end

  def create
  	@player = Player.new
  	if @player.save
  		redirect_to root_path(player_params)
  	end
  end

  def show
  	@player = Player.find_by(params[:id])
  end

  def edit
  	@player = Player.find_by(params[:id])
  end

  def update
  	@player = Player.find_by(params[:id])
  	@player.update(player_params)
  	if @player.save
  		redirect_to root_path(@player.id)
    end
  end
  def destroy
  	@player = Player.find_by(params[:id])
  	@player.destroy
  	redirect_to root_path
  end

  private
  def player_params
  	params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url:update_path(@player.id) do |f|%>

<%= f.label :nickname%>
<%= f.text_field :nickname%></br>

<%= f.label :rank%>
<%= f.text_field :rank%></br>

<%= f.label :charisma%>
<%= f.text_field :charisma%></br>

<%= f.label :wisdom%>
<%= f.text_field :wisdom%></br>

<%= f.submit "Edit"%>

<%end%>

app/views/players/index.html.erb
<%= link_to "New player", new_player_path %>
<%if @players == [] %>
	<p> We can't found player</p>
<% else %>
<% @players.each do |player|%>
	<p> Player <b> <%= player.nickname %> </b> Create </br>
		<%= player.rank %></br>
		<%= player.charisma%></br>
		<%= player.wisdom%></br>
<%= link_to "Read more", player_path(player.id)%></p>
<% end %>
<% end %>

app/views/players/new.html.erb
<%= form_for @player, url:players_path do |f|%>

<%= f.label :nickname%>
<%= f.text_field :nickname%></br>

<%= f.label :rank%>
<%= f.text_field :rank%></br>

<%= f.label :charisma%>
<%= f.text_field :charisma%></br>

<%= f.label :wisdom%>
<%= f.text_field :wisdom%></br>

<%= f.submit "Create"%>

<%end%>

app/views/players/show.html.erb
<p>
	<%= @player.nickname%> create </br>
	Rank: <%= @player.rank%></br>
	Charisma <%= @player.charisma %></br>
	Wisdom <%= @player.wisdom%></br>
</p>

<p>
  <%= link_to "Edit", edit_player_path %>
  <%= link_to "Destroy", player_path(@player.id), method: :delete %>
</p>